#!/usr/bin/env python3

import math
import numpy as np


def main():
  # Quick & dirty: just hard-code shit lol. Assume we're exec'ing from the right folder
  left = []
  right = []
  with open("input.txt") as f:
    for line in f:
      a, b = (int(_) for _ in line.split("   "))
      left.append(a)
      right.append(b)

  left.sort()
  right.sort()

  print("Min left,  max left  = %d, %d" % (left[0], left[-1]))
  print("Min right, max right = %d, %d" % (right[0], right[-1]))

  diff_sum = 0
  for i in range(len(left)):
    diff_sum += int(math.fabs(left[i] - right[i]))

  print("Diff sum: %d" % diff_sum)

  # Part 2 yo!

  similarity_sum = 0
  # Use numpy
  rightnp = np.array(right)
  for entry in left:
    occurrences = len(np.where(rightnp == entry)[0])
    similarity_sum += occurrences * entry

  print("Similarity: %d" % similarity_sum)

if __name__=="__main__":
  main()
