#!/usr/bin/env python3


def read_input():
  with open("input.txt") as fh:
    ids_line = fh.readline()
  ids_line.rstrip()

  id_ranges = ids_line.split(",")
  for id_range in id_ranges:
    start, stop = [int(_) for _ in id_range.split("-", maxsplit=1)]
    # In this problem the ranges are inclusive
    yield range(start, stop+1)


def is_repeating(whole: str, unit: str) -> bool:
  # len(whole) must be a multiple of len(unit)
  if len(whole) % len(unit) != 0:
    return False

  len_quotient = len(whole) // len(unit)
  for i in range(len_quotient-1):
    offset = (i+1) * len(unit)
    next_offset = (i+2) * len(unit)
    slice = whole[offset:next_offset]
    if slice != unit:
      return False

  return True


def is_id_invalid(id: int) -> bool:
  """
  Detects if an ID is invalid or not.
  An ID is invalid if it consists entirely of repeating patterns.
  """
  str_id = str(id)

  # See if the ID is a repeating sequence of digits, starting from single digit "unit".
  half_len = len(str_id) // 2
  for unit_len in range(1, half_len+1):
    unit = str_id[:unit_len]
    if is_repeating(str_id, unit):
      return True

  return False


def main():
  invalid_ids_sum = 0
  for id_range in read_input():
    # print(f"Checking {id_range}")
    for id in id_range:
      if is_id_invalid(id):
        # print(id)
        invalid_ids_sum += id

  print("Invalid IDs sum:")
  print(invalid_ids_sum)


def test():
  result = is_repeating("121212", "12")
  if result != True:
    print("Test FAILED!")
  else:
    print("Test passed.")


if __name__=="__main__":
  main()