#!/usr/bin/env python3


import numpy as np
import operator
import re


OPS = {
  "+": operator.add,
  "*": operator.mul,
}
RE_WHITESPACE = re.compile(r"\s+")


def main():
  # Read input

  table = []
  with open("input.txt") as fh:
    for line in fh:
      entries = RE_WHITESPACE.split(line.strip())
      table.append(entries)

  operators = table[-1]
  all_operands = np.array([[int(entry) for entry in row] for row in table[:-1]])

  n_operands, n_equations = all_operands.shape
  print(f"Input is {n_equations} equations of {n_operands} operands each.")

  # Do calculations

  result_sum = 0
  for eq_id in range(n_equations):
    op = OPS[operators[eq_id]]
    operands = iter(all_operands[:, eq_id])
    result = next(operands)
    for operand in operands:
      result = op(result, operand)
    result_sum += result

  print(f"Sum of all results: {result_sum}")


if __name__=="__main__":
  main()
