#!/usr/bin/env python3
# https://adventofcode.com/2025/day/3


def read_input():
  with open("input.txt") as fh:
    for line in fh:
      bank = [int(digit) for digit in line.rstrip()]
      yield bank


def max_with_position(battery_bank: list[int], start: int, stop: int) -> tuple[int, int]:
  max_joltage = -1
  max_position = None

  if stop <= start:
    raise ValueError(f"stop ({stop}) must be larger than start ({start}).")

  for i in range(start, stop):
    battery_joltage = battery_bank[i]
    if battery_joltage > max_joltage:
      max_joltage = battery_joltage
      max_position = i

  return max_joltage, max_position


def analyze_battery_bank(battery_bank: list[int]) -> int:
  """
  Part 2: must now activate 12 batteries per bank. Need an iterative approach.
  """
  batteries = []
  last_battery_position = -1
  for batteries_selected in range(12):
    battery, last_battery_position = max_with_position(
      battery_bank, last_battery_position+1, len(battery_bank) - (11 - batteries_selected))
    batteries.append(battery)

  joltage = int("".join([str(_) for _ in batteries]))
  return joltage


def main():
  total_joltage = 0
  for battery_bank in read_input():
    total_joltage += analyze_battery_bank(battery_bank)
  print("Total joltage:")
  print(total_joltage)


if __name__=="__main__":
  main()