#!/usr/bin/env python3
# https://adventofcode.com/2024/day/19

from functools import lru_cache


def read_input():
  towels = None
  displays = []
  with open("input.txt") as f:
    # First line: towels
    towels = f.readline().rstrip().split(", ")

    # Blank line
    f.readline()

    # Remaining lines: display patterns
    for line in f:
      line = line.rstrip()
      displays.append(line)

  return towels, displays


def count_arrangements(towel_set, display):
  """
  Counts all possible ways to form `display` using `towels`.
  Uses memoized recursion (DP).
  """

  @lru_cache(None)  # Memoization to avoid redundant calculations
  def dp(i):
    if i == len(display):
      return 1  # Reached end, valid arrangement

    ways = 0
    # display[:len(display)] is the full str so in the range call, need to set 'end' to len(display)+1
    for j in range(i + 1, len(display) + 1):
      if display[i:j] in towel_set:  # Can we form display[i:j]?
        ways += dp(j)  # Recurse on the remainder

    return ways

  return dp(0)


def main():
  towels, displays = read_input()
  towel_set = set(towels)

  total_count = 0
  for display in displays:
    total_count += count_arrangements(towel_set, display)

  print("Total ways to form all requested displays:", total_count)


if __name__=="__main__":
  main()
